const DestinationData = [
  {
    Region: "Africa",
    Country: "South Africa",
    City: "Cape Town",
    AvgTemperature: "16.5",
    Cost_of_Living_Index: "64.0",
    hotel_price_avg: "82",
    budget_transport: "50",
  },
  {
    Region: "Asia",
    Country: "Japan",
    City: "Tokyo",
    AvgTemperature: "15.2",
    Cost_of_Living_Index: "85.0",
    hotel_price_avg: "130",
    budget_transport: "60",
  },
  {
    Region: "Europe",
    Country: "France",
    City: "Paris",
    AvgTemperature: "11.3",
    Cost_of_Living_Index: "70.0",
    hotel_price_avg: "150",
    budget_transport: "55",
  },
  {
    Region: "North America",
    Country: "United States",
    City: "New York",
    AvgTemperature: "13.7",
    Cost_of_Living_Index: "100.0",
    hotel_price_avg: "220",
    budget_transport: "80",
  },
  {
    Region: "South America",
    Country: "Brazil",
    City: "São Paulo",
    AvgTemperature: "20.0",
    Cost_of_Living_Index: "50.0",
    hotel_price_avg: "70",
    budget_transport: "40",
  },
  {
    Region: "Oceania",
    Country: "Australia",
    City: "Sydney",
    AvgTemperature: "18.4",
    Cost_of_Living_Index: "75.0",
    hotel_price_avg: "140",
    budget_transport: "65",
  },
  {
    Region: "Asia",
    Country: "Thailand",
    City: "Bangkok",
    AvgTemperature: "28.0",
    Cost_of_Living_Index: "45.0",
    hotel_price_avg: "40",
    budget_transport: "30",
  },
  {
    Region: "Europe",
    Country: "Italy",
    City: "Rome",
    AvgTemperature: "14.8",
    Cost_of_Living_Index: "68.0",
    hotel_price_avg: "100",
    budget_transport: "50",
  },
  {
    Region: "North America",
    Country: "Canada",
    City: "Toronto",
    AvgTemperature: "10.0",
    Cost_of_Living_Index: "80.0",
    hotel_price_avg: "180",
    budget_transport: "70",
  },
  {
    Region: "Africa",
    Country: "Kenya",
    City: "Nairobi",
    AvgTemperature: "19.0",
    Cost_of_Living_Index: "57.0",
    hotel_price_avg: "55",
    budget_transport: "35",
  },
];
export default DestinationData;
